version: '3'
services:
  streamlit_dashboard:
    image: streamlit:latest
    container_name: streamlit_dashboard_test
    platform: linux/amd64 # platform을 linux/amd64로 변환
    # command: streamlit run /app/streamlit_app.py  # Adjust the path to your Streamlit app file
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app:/app  # Adjust the volume path for your app files
